---
title: "Lab 1 Complete!"
description: "Reflections on my first lab experience in E155."
author: "Jessica Li"
date: "9/9/2026"
categories:
  - reflection
  - labreport
draft: false
---

Wow. This past week was definitely a challenge to say the least. It felt like a sprint to finish, despite the fact that I had started the lab early in the week. I am hopeful that because the first lab meant also getting back up to speed on the tools, software, and hardware, that this first lab took longer than future labs will. I feel much more confident now in my ability to use Radiant and debug projects.

Let's talk about thing's I'm proud of for this week!

1. Started early (I finished most of the Quarto website/portfolio setup before the first class on Monday/Tuesday, and I started the lab on Wednesday.)

2. Finished the Lab on time. 
    + While I am not proud of the large amount of time I had to spent completing this project, I am proud that I stuck with it and finished it anyway.

3. Helped other students in lab. (Community building! I met new people. Definitely a mutually beneficial experience)

4. I feel that I was able to really practice my problem solving skills and design thinking. I was able to think through the problems and create solutions. 

Let's talk about some things I would like to improve on for next week!
1. Overall Time Commitment. 
    + This will come with more practice and experience, but I would like to be able to complete the lab in a more reasonable amount of time. I did not protect my time well enough for my other classes or my own wellbeing (sleep). In summary, I want to work on efficiency, and personal boundaries to my workload balance.

2. Process Efficiency 
    + I need to organize my lab time to coincide with lab help, as well as avoiding the busiest hours in the lab.
    + I need to be more organized in my approach to debugging, when I shouldn't take the instructions at face-value, when I should find other ways to complete the same task, when I should move on and wait for help.

This lab was incredibly fun to complete, despite the consectutive late nights and long hours. I am reminded of how rewarding it is to see a project come together, and I am excited to continue on! Of course, rather expectedly, the process has also reminded me that I need to learn more than just the technical content, but also soft skills like time management, organization, and communication.

Thank you to the grutors and my classmates for all the help and companionship this week :) 

They said this class was community-building and they did not lie.
